language: node_js
node_js:
  - "0.10"
services:
  - postgresql
env:
  - DATABASE_URL="postgres://travis:@localhost/uonline" DATABASE_URL_TEST="postgres://travis:@localhost/uonline_test"
before_script:
  - # test scripts
  - ./init.coffee --info || true
  - ./init.coffee --create-database both --migrate-tables --optimize-tables --test-monsters
  - ./init.coffee --info
  - ./add-admin.coffee admin password
  - ./init.coffee --drop-database both
  - ./init.coffee --info || true
  - # Create test database
  - psql -c 'create database uonline_test;' -U postgres
script:
  - grunt default jscoverage_write_lcov
after_script:
  - cat report.lcov | ./node_modules/coveralls/bin/coveralls.js
