language: node_js
node_js:
  - "stable"
addons:
  postgresql: "9.3"
env:
  - DATABASE_URL="postgres://travis:@localhost/uonline" DATABASE_URL_TEST="postgres://travis:@localhost/uonline_test"
before_script:
  - # test scripts
  - ./init.coffee --info || true
  - ./init.coffee --create-database both --migrate-tables --unify-export --monsters --items --optimize
  - ./init.coffee --info
  - ./add-admin.coffee admin password
  - ./init.coffee --drop-database both
  - ./init.coffee --info || true
  - # Create databases
  - ./init.coffee --create-database both
script:
  - gulp travis
# New stack
sudo: false
cache:
  directories:
  - node_modules
