language: php
php:
  - 5.4
  - 5.5
services:
  - mysql
before_script:
  - make diagnose
  - ./composer.phar install
  - echo "localhost|travis||uonline|off" > keyring
  - ./init.php --info
  - ./init.php --database --tables --unify-validate --unify-export --test-monsters --optimize --drop  # test full cycle
  - ./init.php --info
  - ./init.php --database --tables --unify-validate --unify-export --test-monsters --optimize
  - ./init.php --info
script:
  - make testl
