language: node_js
node_js:
  - "0.10"
services:
  - postgresql
env:
  - DATABASE_URL="postgres://travis:@localhost/uonline" DATABASE_URL_TEST="postgres://travis:@localhost/uonline_test"
before_script:
  - # test scripts
  - ./init.coffee --info || true
  - ./init.coffee --create-database both --migrate-tables --unify-export --monsters --optimize-tables
  - ./init.coffee --info
  - ./add-admin.coffee admin password
  - ./init.coffee --drop-database both
  - ./init.coffee --info || true
  - # Create test database
  - psql -c 'create database uonline_test;' -U postgres
script:
  - grunt travis
