language: php
php:
  - "5.5"
  - "5.4"
services:
  - mysql
  - postgresql
env:
  - DATABASE_URL="postgres://travis:@localhost/uonline" DATABASE_URL_TEST="postgres://travis:@localhost/uonline_test" MYSQL_DATABASE_URL="mysql://travis:@localhost/uonline" MYSQL_DATABASE_URL_TEST="mysql://travis:@localhost/uonline_test"
before_script:
  - # Node.js setup
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install nodejs
  - node --version
  - travis_retry npm install
  - travis_retry npm install -g grunt-cli
  - # PHP setup
  - make diagnose
  - travis_retry ./composer.phar install
  - # Database setup
  - echo "localhost|travis||uonline|off" > keyring
  - ./init.php --info
  - ./init.php --database --tables --unify-validate --unify-export --test-monsters --optimize --drop  # test full cycle
  - ./init.php --info
  - ./init.php --database --tables --unify-validate --unify-export --test-monsters --optimize
  - ./init.php --info
  - mysql -e 'create database uonline_test;'
script:
  - grunt
after_script:
  - ./node_modules/nodeunit/bin/nodeunit tests_node/ --reporter lcov | travis_retry ./node_modules/coveralls/bin/coveralls.js
